/**
 * MandiX - Farm Equipment Rental Marketplace (Custom Hiring Center)
 * Certified machinery catalog, specs, owner details, hourly/daily rental rates and booking manager.
 */

export const EQUIPMENT_CATALOG = [
  {
    id: 'eq_1',
    name: 'Mahindra 575 DI Tractor (45 HP)',
    category: 'Tractor',
    specs: '4 Cylinders, 45 HP, Dual Clutch, Power Steering, High Fuel Efficiency',
    hourlyRate: 350,
    dailyRate: 2200,
    provider: 'Kisan Custom Hiring Center, Chakia',
    phone: '+91 94312 88411',
    location: 'Chakia, East Champaran (3.2 km away)',
    rating: 4.9,
    availability: 'Available Today',
    operatorIncludedOption: true,
    operatorCostPerDay: 400,
    icon: 'fa-tractor',
    isDemo: true
  },
  {
    id: 'eq_2',
    name: 'John Deere 5050D 4WD Tractor (50 HP)',
    category: 'Tractor',
    specs: '50 HP, 4-Wheel Drive, Heavy Duty for deep tillage & puddling',
    hourlyRate: 450,
    dailyRate: 2800,
    provider: 'Tirhut Agri Equipment Hub',
    phone: '+91 98350 21908',
    location: 'Motihari Road, East Champaran (6.5 km away)',
    rating: 4.8,
    availability: 'Available Tomorrow',
    operatorIncludedOption: true,
    operatorCostPerDay: 450,
    icon: 'fa-tractor',
    isDemo: true
  },
  {
    id: 'eq_3',
    name: 'Preet 987 Combine Harvester (Multi-Crop)',
    category: 'Harvester',
    specs: 'Self-propelled 101 HP engine, 14 ft cutter bar for Paddy & Wheat harvesting',
    hourlyRate: 1600,
    dailyRate: 11000,
    provider: 'North Bihar Harvester Syndicate',
    phone: '+91 97711 44521',
    location: 'Muzaffarpur Bypass (18 km away)',
    rating: 4.7,
    availability: 'Slot Booking Required (3 days advance)',
    operatorIncludedOption: true,
    operatorCostPerDay: 600,
    icon: 'fa-truck-monster',
    isDemo: true
  },
  {
    id: 'eq_4',
    name: 'Shaktiman 7 Feet Rotary Tiller (Rotavator)',
    category: 'Rotavator',
    specs: '48 L-type boron steel blades, multi-speed gearbox, optimal for fine seedbed prep',
    hourlyRate: 250,
    dailyRate: 1500,
    provider: 'Gramin Sahayata Kendra',
    phone: '+91 93041 90223',
    location: 'Pipra Block, East Champaran (5.1 km away)',
    rating: 4.9,
    availability: 'Available Today',
    operatorIncludedOption: false,
    icon: 'fa-dharmachakra',
    isDemo: true
  },
  {
    id: 'eq_5',
    name: 'Happy Seeder / Zero-Till Seed Drill (9 Tynes)',
    category: 'Seed drill',
    specs: 'Direct wheat sowing into paddy straw without burning residue, saves water & fertilizer',
    hourlyRate: 300,
    dailyRate: 1800,
    provider: 'Soil Conservation Co-op, Mehsi',
    phone: '+91 91223 77890',
    location: 'Mehsi Block (7.8 km away)',
    rating: 4.8,
    availability: 'Available Today',
    operatorIncludedOption: true,
    operatorCostPerDay: 350,
    icon: 'fa-seedling',
    isDemo: true
  },
  {
    id: 'eq_6',
    name: 'VST Shakti 130 DI Power Tiller (13 HP)',
    category: 'Power tiller',
    specs: 'Compact 13 HP diesel tiller, ideal for vegetable gardens, orchards & small plots',
    hourlyRate: 180,
    dailyRate: 1100,
    provider: 'Laghu Kisan Seva',
    phone: '+91 99341 66211',
    location: 'Kalyanpur (4.5 km away)',
    rating: 4.6,
    availability: 'Available Today',
    operatorIncludedOption: false,
    icon: 'fa-wrench',
    isDemo: true
  },
  {
    id: 'eq_7',
    name: 'Multi-Crop High Output Thresher',
    category: 'Thresher',
    specs: 'Threshes Wheat, Gram, Mustard, Soybean with 99% grain purity & straw chopper',
    hourlyRate: 400,
    dailyRate: 2400,
    provider: 'Champaran Krishi Machinery',
    phone: '+91 94701 55210',
    location: 'Chakia East (2.0 km away)',
    rating: 4.8,
    availability: 'Available Today',
    operatorIncludedOption: true,
    operatorCostPerDay: 400,
    icon: 'fa-gears',
    isDemo: true
  },
  {
    id: 'eq_8',
    name: 'Hydraulic Tipping Agricultural Trolley (5 Ton)',
    category: 'Trolley',
    specs: 'Dual axle 5-ton payload hydraulic tipper for mandi grain transport & compost carrying',
    hourlyRate: 150,
    dailyRate: 900,
    provider: 'Bhoomi Parivahan Kendra',
    phone: '+91 98355 44102',
    location: 'Chakia Mandi Gate #2',
    rating: 4.7,
    availability: 'Available Today',
    operatorIncludedOption: false,
    icon: 'fa-trailer',
    isDemo: true
  }
];

export const EQUIPMENT_CATEGORIES = [
  'All',
  'Tractor',
  'Harvester',
  'Rotavator',
  'Seed drill',
  'Power tiller',
  'Thresher',
  'Trolley'
];
