/**
 * MandiX - Doorstep Fertilizer Delivery Service
 * Catalog of certified fertilizers, crop-based recommendation filter, cart, and order tracking.
 */

export const FERTILIZER_CATALOG = [
  {
    id: 'fert_1',
    name: 'IFFCO Neem Coated Urea (45 kg)',
    brand: 'IFFCO (सहकारी समिति)',
    category: 'Urea',
    crops: ['Wheat (गेहूं)', 'Paddy (धान)', 'Maize (मक्का)', 'Sugarcane (गन्ना)'],
    price: 266.50,
    mrp: 266.50,
    unit: '45 kg Bag',
    subsidyNote: 'भारत सरकार द्वारा राजसहायता प्राप्त (Govt Subsidized Rate)',
    composition: '46% Nitrogen (N)',
    dosage: '1 Bag / Acre (Top dressing)',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-bag-shopping',
    rating: 4.8,
    isDemo: true
  },
  {
    id: 'fert_2',
    name: 'IFFCO Nano Urea (500 ml Liquid)',
    brand: 'IFFCO Innovation',
    category: 'Bio-fertilizer',
    crops: ['Wheat (गेहूं)', 'Paddy (धान)', 'Vegetables (सब्जियां)', 'Mustard (सरसों)'],
    price: 225.00,
    mrp: 225.00,
    unit: '500 ml Bottle',
    subsidyNote: '1 बोतल = 1 बोरी यूरिया के बराबर प्रभाव',
    composition: '4% Total Nitrogen (Nano Scale)',
    dosage: '2-4 ml per Litre water (Foliar spray)',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-bottle-droplet',
    rating: 4.9,
    isDemo: true
  },
  {
    id: 'fert_3',
    name: 'DAP 18:46:0 (50 kg)',
    brand: 'KRIBHCO / IFFCO',
    category: 'DAP',
    crops: ['Wheat (गेहूं)', 'Potato (आलू)', 'Mustard (सरसों)', 'Pulses (दलहन)'],
    price: 1350.00,
    mrp: 1350.00,
    unit: '50 kg Bag',
    subsidyNote: 'सब्सिडी दर (DAP Subsidized Bag)',
    composition: '18% N, 46% Phosphate (P2O5)',
    dosage: '50 kg / Acre at sowing time (Basal dose)',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-sack-xmark',
    rating: 4.7,
    isDemo: true
  },
  {
    id: 'fert_4',
    name: 'NPK 12:32:16 Complex Fertilizer',
    brand: 'PARADEEP / GSFC',
    category: 'NPK',
    crops: ['Paddy (धान)', 'Cotton (कपास)', 'Sugarcane (गन्ना)', 'Vegetables'],
    price: 1470.00,
    mrp: 1470.00,
    unit: '50 kg Bag',
    subsidyNote: 'संतुलित पोषण (Balanced Soil Nutrition)',
    composition: '12% N, 32% P, 16% K',
    dosage: '75 kg / Acre',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-layer-group',
    rating: 4.6,
    isDemo: true
  },
  {
    id: 'fert_5',
    name: 'MOP - Muriate of Potash (50 kg)',
    brand: 'IPL (Indian Potash Ltd)',
    category: 'MOP',
    crops: ['Potato (आलू)', 'Sugarcane (गन्ना)', 'Banana', 'Tomato (टमाटर)'],
    price: 1700.00,
    mrp: 1700.00,
    unit: '50 kg Bag',
    subsidyNote: 'रोग प्रतिरोधक व कंद विकास',
    composition: '60% Potash (K2O)',
    dosage: '25-30 kg / Acre',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-cubes',
    rating: 4.7,
    isDemo: true
  },
  {
    id: 'fert_6',
    name: 'Zinc Sulphate Monohydrate 33% (5 kg)',
    brand: 'Utkarsh Agro',
    category: 'Micronutrients',
    crops: ['Paddy (खैरा रोग बचाव)', 'Wheat (गेहूं)', 'Maize (मक्का)'],
    price: 480.00,
    mrp: 480.00,
    unit: '5 kg Pack',
    subsidyNote: 'जिंक की कमी से होने वाले रोगों से सुरक्षा',
    composition: '33% Zinc (Zn) + 15% Sulphur',
    dosage: '5 kg / Acre at basal stage',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-flask',
    rating: 4.8,
    isDemo: true
  },
  {
    id: 'fert_7',
    name: 'IFFCO Jaivik Vermicompost (Organic, 50 kg)',
    brand: 'IFFCO Kisan Organic',
    category: 'Organic fertilizers',
    crops: ['All Crops (सभी फसलों व सब्जियों के लिए)'],
    price: 390.00,
    mrp: 390.00,
    unit: '50 kg Bag',
    subsidyNote: '100% शुद्ध जैविक केंचुआ खाद',
    composition: 'Organic Matter > 30%, Trichoderma Enriched',
    dosage: '200-400 kg / Acre',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-leaf',
    rating: 4.9,
    isDemo: true
  },
  {
    id: 'fert_8',
    name: 'Azotobacter & PSB Bio-Fertilizer Culture',
    brand: 'National Biofertilizers',
    category: 'Bio-fertilizers',
    crops: ['Wheat (गेहूं)', 'Gram (चना)', 'Paddy (धान)', 'Mustard (सरसों)'],
    price: 180.00,
    mrp: 180.00,
    unit: '1 Litre Liquid Consortia',
    subsidyNote: 'नाइट्रोजन स्थिरीकरण एवं फास्फोरस घुलनशील',
    composition: 'Live microbial consortia > 10^8 CFU/ml',
    dosage: 'Seed treatment (10 ml / kg seed)',
    stockStatus: 'In Stock (उपलब्ध)',
    imageIcon: 'fa-seedling',
    rating: 4.8,
    isDemo: true
  }
];

export const FERTILIZER_CATEGORIES = [
  'All',
  'Urea',
  'DAP',
  'NPK',
  'MOP',
  'Micronutrients',
  'Organic fertilizers',
  'Bio-fertilizers'
];
